version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: library
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
