services:
  mysql:
    image: mysql:8.3
    container_name: mysql-grpc-gateway
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3307:3306
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - microservices

  author-service:
    container_name: author-service
    build:
      context: .
      dockerfile: ./services/docker/author-service/Dockerfile
    environment:
      AUTHOR_GRPC_PORT: 9092
      OTEL_SERVICE_NAME: author-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    ports:
      - "9092:9092"
    volumes:
      - ./services/author-service:/app/services/author-service
    networks:
      - microservices
    depends_on:
      - mysql
      - jaeger

  book-service:
    container_name: book-service
    build:
      context: .
      dockerfile: ./services/docker/book-service/Dockerfile
    environment:
      BOOK_GRPC_PORT: 9091
      OTEL_SERVICE_NAME: book-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    ports:
      - "9091:9091"
    volumes:
      - ./services/book-service:/app/services/book-service
    networks:
      - microservices
    depends_on:
      - mysql
      - author-service
      - jaeger

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./services/docker/gateway/Dockerfile
    environment:
      GATEWAY_PORT: 8080
      OTEL_SERVICE_NAME: gateway
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    ports:
      - "8080:8080"
    volumes:
      - ./services/gateway:/app/services/gateway
    networks:
      - microservices
    depends_on:
      - book-service
      - author-service
      - jaeger

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16687:16686" # Jaeger UI
      - "4320:4317" # OTLP gRPC receiver
      - "4321:4318" # OTLP HTTP receiver
    networks:
      - microservices

networks:
  microservices:
