// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authors.sql

package author_repository_impl

import (
	"context"
	"time"
)

const getByID = `-- name: GetByID :one
SELECT id, name, bio, created_at FROM authors WHERE id = ?
`

type GetByIDRow struct {
	ID        int64
	Name      string
	Bio       string
	CreatedAt time.Time
}

func (q *Queries) GetByID(ctx context.Context, id int64) (GetByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}
