// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package book_repository_impl

import (
	"context"
	"time"
)

const getByID = `-- name: GetByID :one
SELECT id, title, author_id, created_at FROM books WHERE id = ?
`

type GetByIDRow struct {
	ID        int64
	Title     string
	AuthorID  int64
	CreatedAt time.Time
}

func (q *Queries) GetByID(ctx context.Context, id int64) (GetByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
